### ISSUE TITLE
game crashed

### ISSUE THREAD

**Issue by NCPUser** [Pr3roxDLC/Catalyst#19]
Logs

[2022-10-16-7.log](https://github.com/Pr3roxDLC/Catalyst/files/9795305/2022-10-16-7.log)

**Comment by Pr3roxDLC** [comment]
okay, ive never seen this, seems like there are a couple of issues here, can you 1. discribe what you did so we can maybe try to recreate your crash and 2. try playing the game without optifine, this has been known to cause issues in the past too, so maybe i havent completly fixed all optifine related issues

**Comment by NCPUser** [comment]
Xm okey im pop totem player my game no particle on blocks on crash.
