### ISSUE TITLE
major skid

### ISSUE THREAD

**Issue by pastimee** [Pr3roxDLC/Catalyst#9]
major

**Comment by Tarkan-Zarrouk** [comment]
Closed because this was a known issue lmao. **Gishcode classes** :trollface:

**Comment by pastimee** [comment]
> Closed because this was a known issue lmao. **Gishcode classes** :trollface:

that's not even the worst part mane ....

**Comment by Tarkan-Zarrouk** [comment]
no the worst part is that catalyst exists

**Comment by therealbush** [comment]
catashit

**Comment by Zane2b2t** [comment]
CTAlyst
